# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BSIT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_Teacher', models.CharField(max_length=1000)),
                ('Class_Title', models.CharField(max_length=500)),
                ('University', models.CharField(max_length=500)),
                ('Class_Logo', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10)),
                ('student_Name', models.CharField(max_length=20)),
                ('bsit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloworld.BSIT')),
            ],
        ),
    ]
